name: docker build & push

on:
  push:
    branches: [main]

jobs:
  BuildAndPush:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: login to docker hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: docker build & push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: gizmooao/utterances-oauth-go:latest
