name: docker build & push

on:
  push:
    branches: [master]

jobs:
  BuildAndPush:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - uses: actions/setup-go@v2
        with:
          go-version: '^1.15.6'

      - name: build
        env:
          GOOS: linux
          GOARCH: amd64
        run: go build -ldflags "-s -w" -o="goapp"

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: login to docker hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: docker build & push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: gizmooao/utterances-oauth-go:latest
